stages:
  - test
  - build
  - deploy

unit-test-job:
  stage: test
  image: node
  script:
    - echo "Testing App"
    - yarn install
    - CI=true yarn lint
    - CI=true yarn test
    - echo "Test successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
     - node_modules/

build-job:
  stage: build
  image: node
  script: 
   - echo "Start building App"
   - yarn build
   - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
     - build

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
